/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DangNhap;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanLyLopHoc extends javax.swing.JPanel {
    DefaultTableModel model = new DefaultTableModel();
    SimpleDateFormat ngay = new SimpleDateFormat("dd/MM/yyyy");
    /**
     * Creates new form QuanLyLopHoc
     */
    public QuanLyLopHoc() {
        initComponents();
        taiDuLieu();
        taiComboboxma_kh();
        taiComboboxma_hv();
    }
    public void taiDuLieu() {         
        try {
            DBConnection a = new DBConnection();
            Connection conn = a.getConnection();
            int so;
            Vector hang,cot;
            cot = new Vector();
            Statement ps = conn.createStatement();
            ResultSet rs = ps.executeQuery("SELECT * FROM lop_hoc");
            ResultSetMetaData metadata = rs.getMetaData();
            so = metadata.getColumnCount();
                model.setColumnIdentifiers(new Object[]{
                    "Mã Lớp Học","Mã Khóa Học","Mã Học Viên","Ngày Đăng Ký","Tình Trạng"
                });
        
            while(rs.next()) {
                hang = new Vector();
                for(int i=1;i<=so;i++) {
                    hang.addElement(rs.getString(i));
                
                }
                model.addRow(hang);
                jTable1.setModel(model);
            }
            
            jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(jTable1.getSelectedRow()>=0) { 
                    tfmlh.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0)+"");
                    cbxmkh.setSelectedItem(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1)+""); 
                    cbxmhv.setSelectedItem(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2)+""); 
                    tfndk.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3)+"");
                }
            }
        } );
 
        } catch (Exception e) {
            System.out.println(e.toString());
        }       
    }
    public void taiComboboxma_kh() {
        try {
            DBConnection a = new DBConnection();
            Connection conn = a.getConnection();
            PreparedStatement sp = conn.prepareStatement("SELECT ma_khoa_hoc FROM khoa_hoc GROUP BY ma_khoa_hoc");
            ResultSet rs = sp.executeQuery();           
            while(rs.next()) {
                cbxmkh.addItem(rs.getString("ma_khoa_hoc"));
            }         
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    public void taiComboboxma_hv() {
        try {
            DBConnection a = new DBConnection();
            Connection conn = a.getConnection();
            PreparedStatement sp = conn.prepareStatement("SELECT ma_hoc_vien FROM hoc_vien1 GROUP BY ma_hoc_vien");
            ResultSet rs = sp.executeQuery();           
            while(rs.next()) {
                cbxmhv.addItem(rs.getString("ma_hoc_vien"));
            }         
        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpnRoot1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfmlh = new javax.swing.JTextField();
        tfndk = new javax.swing.JTextField();
        chkth = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        cbxmhv = new javax.swing.JComboBox<>();
        cbxmkh = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Moi = new javax.swing.JButton();
        CapNhat = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        TaiLai = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtfSearch1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        jpnRoot1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÝ LỚP HỌC");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã lớp học");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Mã khóa học");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ngày đăng ký");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Trạng thái");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Mã học viên");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfmlh)
                            .addComponent(cbxmkh, 0, 229, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel4))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfndk, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxmhv, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel7)
                        .addGap(69, 69, 69)
                        .addComponent(chkth)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfmlh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cbxmhv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfndk, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cbxmkh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(chkth))
                .addGap(26, 26, 26))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable1);

        Moi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Moi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new-icon-16.png"))); // NOI18N
        Moi.setText("Tạo mới");
        Moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoiActionPerformed(evt);
            }
        });

        CapNhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-document-edit-icon-16.png"))); // NOI18N
        CapNhat.setText("Sửa");
        CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapNhatActionPerformed(evt);
            }
        });

        Xoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-edit-delete-icon-16.png"))); // NOI18N
        Xoa.setText("Xóa");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        TaiLai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TaiLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-refresh-shield-50 (1).png"))); // NOI18N
        TaiLai.setText("Tải Lại");
        TaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaiLaiActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Mã lớp học");

        jtfSearch1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-icon-24.png"))); // NOI18N
        jButton3.setText("Tìm kiếm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnRoot1Layout = new javax.swing.GroupLayout(jpnRoot1);
        jpnRoot1.setLayout(jpnRoot1Layout);
        jpnRoot1Layout.setHorizontalGroup(
            jpnRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRoot1Layout.createSequentialGroup()
                .addGroup(jpnRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4)
                    .addGroup(jpnRoot1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jpnRoot1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnRoot1Layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jLabel9)
                                .addGap(74, 74, 74)
                                .addComponent(jtfSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jButton3)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnRoot1Layout.createSequentialGroup()
                        .addGroup(jpnRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnRoot1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(Moi)
                                .addGap(67, 67, 67)
                                .addComponent(CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(TaiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnRoot1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnRoot1Layout.setVerticalGroup(
            jpnRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRoot1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jpnRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnRoot1Layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRoot1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpnRoot1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Moi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TaiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot1, javax.swing.GroupLayout.PREFERRED_SIZE, 988, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 963, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jtfSearch.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Bạn chưa nhập thông tin tìm kiếm");
        } else {
            try {
                DBConnection a = new DBConnection();
                Connection conn = a.getConnection();
                PreparedStatement sp = conn.prepareStatement("SELECT * FROM lop_hoc WHERE ma_lop_hoc =?");
                sp.setString(1,jtfSearch.getText());
                ResultSet rs = sp.executeQuery();
                //boolean ktr = rs.next();
                if(rs.next()==true) {
                    tfmlh.setText(rs.getString("ma_lop_hoc"));
                    cbxmkh.addItem(rs.getString("ma_khoa_hoc"));
                    cbxmhv.addItem(rs.getString("ma_hoc_vien"));
                    tfndk.setText(rs.getString("ngay_dang_ky"));
                    chkth.setText(rs.getString("tinh_trang"));

                }else {
                    JOptionPane.showMessageDialog(this,"Không tìm thấy lớp học");
                    jtfSearch.setText("");
                }

            } catch (Exception e) {
                System.out.println(e.toString());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void MoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoiActionPerformed
        if(tfmlh.getText().isEmpty()
            ||tfndk.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin");
        }
        else
        {
            try {
                DBConnection a = new DBConnection();
                Connection conn = a.getConnection();
                PreparedStatement sp = conn.prepareStatement("INSERT INTO lop_hoc(ma_lop_hoc,ma_khoa_hoc,ma_hoc_vien,ngay_dang_ky,tinh_trang)"
                    + "VALUES(?,?,?,?,?)");
                sp.setString(1,tfmlh.getText());
                sp.setString(2,cbxmkh.getSelectedItem().toString());
                sp.setString(3,cbxmhv.getSelectedItem().toString());
                sp.setString(4,tfndk.getText());
                boolean th = false;
                if(chkth.isSelected()) {
                    th = true;
                }
                sp.setBoolean(5, th);

                if(sp.executeUpdate()>0){
                    JOptionPane.showMessageDialog(this, "Thêm Thành Công!");
                    model.setRowCount(0);
                    taiDuLieu();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Lỗi");
                System.out.println(e.toString());
            }
        }
    }//GEN-LAST:event_MoiActionPerformed

    private void CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapNhatActionPerformed
        if(tfmlh.getText().isEmpty()
            ||tfndk.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dữ liệu để sửa");
        }
        else
        {
            try {
                DBConnection a = new DBConnection();
                Connection conn = a.getConnection();
                PreparedStatement sp = conn.prepareStatement("UPDATE lop_hoc SET  ngay_dang_ky=?,tinh_trang=? WHERE ma_lop_hoc =? and ma_khoa_hoc =? and ma_hoc_vien =?");
                sp.setString(3,tfmlh.getText());
                sp.setString(4,cbxmkh.getSelectedItem().toString());
                sp.setString(5,cbxmhv.getSelectedItem().toString());
                sp.setString(1,tfndk.getText());
                boolean th = false;
                if(chkth.isSelected()) {
                    th = true;
                }
                sp.setBoolean(2, th);
                sp.executeUpdate();
                JOptionPane.showMessageDialog(this, "Sửa Thành Công!");
                model.setRowCount(0);
                taiDuLieu();
            } catch (Exception e) {
                System.out.println(e.toString());
            }
        }
    }//GEN-LAST:event_CapNhatActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        if(tfmlh.getText().isEmpty()
            ||tfndk.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dữ liệu để xóa");
        }
        else
        {
            try {
                DBConnection a = new DBConnection();
                Connection conn = a.getConnection();
                PreparedStatement sp = conn.prepareStatement("DELETE lop_hoc WHERE ma_lop_hoc =?");
                if(jTable1.getColumnCount()==0){
                    JOptionPane.showConfirmDialog(this,"Bảng Trống");
                }else {
                    sp.setString(1,jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
                    if(JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa lớp học này không?", "Xóa",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    sp.executeUpdate();
                    model.setRowCount(0);
                    taiDuLieu();
                }
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
        }
    }//GEN-LAST:event_XoaActionPerformed

    private void TaiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaiLaiActionPerformed
        tfmlh.setText("");
        tfndk.setText("");
    }//GEN-LAST:event_TaiLaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CapNhat;
    private javax.swing.JButton Moi;
    private javax.swing.JButton TaiLai;
    private javax.swing.JButton Xoa;
    private javax.swing.JComboBox<String> cbxmhv;
    private javax.swing.JComboBox<String> cbxmkh;
    private javax.swing.JCheckBox chkth;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnRoot1;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextField jtfSearch1;
    private javax.swing.JTextField tfmlh;
    private javax.swing.JTextField tfndk;
    // End of variables declaration//GEN-END:variables
}
