/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DangNhap;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

public class QuanLyKhoaHoc extends javax.swing.JPanel {

    DefaultTableModel model = new DefaultTableModel();
    SimpleDateFormat ngay = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form QuanLyKhoaHoc
     */
    public QuanLyKhoaHoc() {
        initComponents();
        taiDuLieu();
    }

    public void taiDuLieu() {
        try {
            DBConnection a = new DBConnection();
            Connection conn = a.getConnection();
            int so;
            Vector hang, cot;
            cot = new Vector();
            Statement ps = conn.createStatement();
            ResultSet rs = ps.executeQuery("SELECT * FROM khoa_hoc");
            ResultSetMetaData metadata = rs.getMetaData();
            so = metadata.getColumnCount();
            model.setColumnIdentifiers(new Object[]{
                "Mã Khóa Học", "Tên Khóa Học", "Tên Giảng Viên", "Mô tả", "Tổng số học viên", "Ngày Bắt Đầu", "Ngày Kết Thúc", "Tình Trạng"
            });

            while (rs.next()) {
                hang = new Vector();
                for (int i = 1; i <= so; i++) {
                    hang.addElement(rs.getString(i));

                }
                model.addRow(hang);
                jTable1.setModel(model);
            }

            jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent e) {
                    if (jTable1.getSelectedRow() >= 0) {
                        tfmkh.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 0) + "");
                        tftkh.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 1) + "");
                        tftgv.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 2) + "");
                        tamta.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 3) + "");
                        tftso.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 4) + "");
                        tfnbd.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 5) + "");
                        tfnkt.setText(jTable1.getValueAt(jTable1.getSelectedRow(), 6) + "");

                    }
                }
            });

        } catch (Exception e) {
            System.out.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jtfSearch = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfmkh = new javax.swing.JTextField();
        tftkh = new javax.swing.JTextField();
        tfnbd = new javax.swing.JTextField();
        tfnkt = new javax.swing.JTextField();
        tftso = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tamta = new javax.swing.JTextArea();
        chkth = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        tftgv = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        Moi = new javax.swing.JButton();
        CapNhat = new javax.swing.JButton();
        Xoa = new javax.swing.JButton();
        TaiLai = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jpnRoot.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtfSearch.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-icon-24.png"))); // NOI18N
        jButton2.setText("Tìm kiếm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Mã khóa học");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(73, 73, 73)
                .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(jButton2)
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÝ KHÓA HỌC");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã khóa học");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tên khóa học");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Ngày bắt đầu");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Ngày kết thúc");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Tổng số học viên");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Trạng thái");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Mô tả");

        tftkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftkhActionPerformed(evt);
            }
        });

        tamta.setColumns(20);
        tamta.setRows(5);
        jScrollPane2.setViewportView(tamta);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Tên giảng viên");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chkth)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfmkh, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tftso)
                                    .addComponent(tfnkt)
                                    .addComponent(tfnbd)
                                    .addComponent(tftkh)
                                    .addComponent(tftgv)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(174, 174, 174))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfmkh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tftkh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tftgv, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(tfnbd, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfnkt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(tftso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(68, 68, 68))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(chkth))))
        );

        Moi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Moi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/new-icon-16.png"))); // NOI18N
        Moi.setText("Tạo mới");
        Moi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoiActionPerformed(evt);
            }
        });

        CapNhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-document-edit-icon-16.png"))); // NOI18N
        CapNhat.setText("Sửa");
        CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapNhatActionPerformed(evt);
            }
        });

        Xoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Close-icon-16.png"))); // NOI18N
        Xoa.setText("Xóa");
        Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaActionPerformed(evt);
            }
        });

        TaiLai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TaiLai.setText("Tải Lại");
        TaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaiLaiActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator3)
            .addComponent(jSeparator4)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnRootLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnRootLayout.createSequentialGroup()
                                .addComponent(Moi)
                                .addGap(49, 49, 49)
                                .addComponent(CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(TaiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53))))
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnRootLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(410, 410, 410))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnRootLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)))
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Moi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TaiLai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jtfSearch.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"Bạn chưa nhập thông tin tìm kiếm");
        } else {
            try {
                DBConnection a = new DBConnection();
                Connection conn = a.getConnection();
                PreparedStatement sp = conn.prepareStatement("SELECT * FROM khoa_hoc WHERE ma_khoa_hoc =?");
                sp.setString(1,jtfSearch.getText());
                ResultSet rs = sp.executeQuery();
                //boolean ktr = rs.next();
                if(rs.next()==true) {
                    tfmkh.setText(rs.getString("ma_khoa_hoc"));
                    tftkh.setText(rs.getString("ten_khoa_hoc"));
                    tftgv.setText(rs.getString("ten_gv"));
                    tamta.setText(rs.getString("mo_ta"));
                    tftso.setText(rs.getString("tong_so_hoc_vien"));
                    tfnbd.setText(rs.getString("ngay_bat_dau"));
                    tfnkt.setText(rs.getString("ngay_ket_thuc"));
                    chkth.setText(rs.getString("tinh_trang"));
                }else {
                    JOptionPane.showMessageDialog(this,"Không tìm thấy khóa học");
                    jtfSearch.setText("");
                }

            } catch (Exception e) {
                System.out.println(e.toString());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tftkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftkhActionPerformed

    private void MoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoiActionPerformed
        if(tfmkh.getText().isEmpty()
            ||tftkh.getText().isEmpty()
            ||tftgv.getText().isEmpty()
            ||tftso.getText().isEmpty()
            ||tfnbd.getText().isEmpty()
            ||tfnkt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập đủ thông tin");
        }
        else
        {
            try {
                DBConnection a = new DBConnection();
                Connection conn = a.getConnection();
                PreparedStatement sp = conn.prepareStatement("INSERT INTO khoa_hoc(ma_khoa_hoc,ten_khoa_hoc,ten_gv,mo_ta,tong_so_hoc_vien,ngay_bat_dau,ngay_ket_thuc,tinh_trang)"
                    + "VALUES(?,?,?,?,?,?,?,?)");
                sp.setString(1,tfmkh.getText());
                sp.setString(2,tftkh.getText());
                sp.setString(3,tftgv.getText());
                sp.setString(4,tamta.getText());
                sp.setInt(5,Integer.parseInt(tftso.getText()));
                sp.setString(6,tfnbd.getText());
                sp.setString(7,tfnkt.getText());
                boolean th = false;
                if(chkth.isSelected()) {
                    th = true;
                }
                sp.setBoolean(8, th);

                if(sp.executeUpdate()>0){
                    JOptionPane.showMessageDialog(this, "Thêm Thành Công!");
                    model.setRowCount(0);
                    taiDuLieu();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Lỗi");
                System.out.println(e.toString());
            }
        }
    }//GEN-LAST:event_MoiActionPerformed

    private void CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapNhatActionPerformed
        if(tfmkh.getText().isEmpty()
            ||tftkh.getText().isEmpty()
            ||tftgv.getText().isEmpty()
            ||tftso.getText().isEmpty()
            ||tfnbd.getText().isEmpty()
            ||tfnkt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dữ liệu để sửa");
        }
        else
        {
            try {
                DBConnection a = new DBConnection();
                Connection conn = a.getConnection();
                PreparedStatement sp = conn.prepareStatement("UPDATE khoa_hoc SET ten_khoa_hoc=?,ten_gv=?,mo_ta=?, tong_so_hoc_vien=?,ngay_bat_dau=?,ngay_ket_thuc=?, tinh_trang=? WHERE ma_khoa_hoc=?");
                sp.setString(8,tfmkh.getText());
                sp.setString(1,tftkh.getText());
                sp.setString(2,tftgv.getText());
                sp.setString(3,tamta.getText());
                sp.setInt(4,Integer.parseInt(tftso.getText()));
                sp.setString(5,tfnbd.getText());
                sp.setString(6,tfnkt.getText());
                boolean th = false;
                if(chkth.isSelected()) {
                    th = true;
                }
                sp.setBoolean(7, th);
                sp.executeUpdate();
                JOptionPane.showMessageDialog(this, "Sửa Thành Công!");
                model.setRowCount(0);
                taiDuLieu();
            } catch (Exception e) {
                System.out.println(e.toString());
            }
        }
    }//GEN-LAST:event_CapNhatActionPerformed

    private void XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaActionPerformed
        if(tfmkh.getText().isEmpty()
            ||tftkh.getText().isEmpty()
            ||tftgv.getText().isEmpty()
            ||tftso.getText().isEmpty()
            ||tfnbd.getText().isEmpty()
            ||tfnkt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn dữ liệu để xóa");
        }
        else
        {
            try {
                DBConnection a = new DBConnection();
                Connection conn = a.getConnection();
                PreparedStatement sp = conn.prepareStatement("DELETE khoa_hoc WHERE ma_khoa_hoc=?");
                if(jTable1.getColumnCount()==0){
                    JOptionPane.showConfirmDialog(this,"Bảng Trống");
                }else {
                    sp.setString(1,jTable1.getValueAt(jTable1.getSelectedRow(),0).toString());
                    if(JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa khóa học này không?", "Xóa",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    sp.executeUpdate();
                    model.setRowCount(0);
                    taiDuLieu();
                }
            }

        } catch (Exception e) {
            System.out.println(e.toString());
        }
        }
    }//GEN-LAST:event_XoaActionPerformed

    private void TaiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaiLaiActionPerformed
        tfmkh.setText("");
        tftkh.setText("");
        tftgv.setText("");
        tftso.setText("");
        tfnbd.setText("");
        tfnkt.setText("");
        tamta.setText("");
    }//GEN-LAST:event_TaiLaiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CapNhat;
    private javax.swing.JButton Moi;
    private javax.swing.JButton TaiLai;
    private javax.swing.JButton Xoa;
    private javax.swing.JCheckBox chkth;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JTextField jtfSearch;
    private javax.swing.JTextArea tamta;
    private javax.swing.JTextField tfmkh;
    private javax.swing.JTextField tfnbd;
    private javax.swing.JTextField tfnkt;
    private javax.swing.JTextField tftgv;
    private javax.swing.JTextField tftkh;
    private javax.swing.JTextField tftso;
    // End of variables declaration//GEN-END:variables
}
